version: '3'
services:
  db:
    image: postgres
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - db
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"